/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArquiteturaRouteImport } from './routes/arquitetura'
import { Route as BairrosRouteImport } from './routes/bairros'
import { Route as EventoRouteImport } from './routes/evento'
import { Route as ImovelIdRouteImport } from './routes/imovel.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquiteturaRoute = ArquiteturaRouteImport.update({
  id: '/arquitetura',
  path: '/arquitetura',
  getParentRoute: () => rootRouteImport,
} as any)
const BairrosRoute = BairrosRouteImport.update({
  id: '/bairros',
  path: '/bairros',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoRoute = EventoRouteImport.update({
  id: '/evento',
  path: '/evento',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelIdRoute = ImovelIdRouteImport.update({
  id: '/imovel/$id',
  path: '/imovel/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquitetura': typeof ArquiteturaRoute
  '/bairros': typeof BairrosRoute
  '/evento': typeof EventoRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquitetura': typeof ArquiteturaRoute
  '/bairros': typeof BairrosRoute
  '/evento': typeof EventoRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquitetura': typeof ArquiteturaRoute
  '/bairros': typeof BairrosRoute
  '/evento': typeof EventoRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arquitetura' | '/bairros' | '/evento' | '/imovel/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arquitetura' | '/bairros' | '/evento' | '/imovel/$id'
  id: '__root__' | '/' | '/arquitetura' | '/bairros' | '/evento' | '/imovel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquiteturaRoute: typeof ArquiteturaRoute
  BairrosRoute: typeof BairrosRoute
  EventoRoute: typeof EventoRoute
  ImovelIdRoute: typeof ImovelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquitetura': {
      id: '/arquitetura'
      path: '/arquitetura'
      fullPath: '/arquitetura'
      preLoaderRoute: typeof ArquiteturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bairros': {
      id: '/bairros'
      path: '/bairros'
      fullPath: '/bairros'
      preLoaderRoute: typeof BairrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento': {
      id: '/evento'
      path: '/evento'
      fullPath: '/evento'
      preLoaderRoute: typeof EventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$id': {
      id: '/imovel/$id'
      path: '/imovel/$id'
      fullPath: '/imovel/$id'
      preLoaderRoute: typeof ImovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquiteturaRoute: ArquiteturaRoute,
  BairrosRoute: BairrosRoute,
  EventoRoute: EventoRoute,
  ImovelIdRoute: ImovelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
